#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------
version: "3.7"
services:
  dotnet:
    image: parc1val/codespaces-example-multicontainer:demo
    container_name: dotnet
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
    environment: 
      - ASPNETCORE_ENVIRONMENT=Codespaces
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined  
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: example

  